### ISSUE TITLE
skapa hushållsmedlem

### ISSUE THREAD

**Issue by FridaUltra** [Byteconjurer/Householding#95]
När man skapar ett nytt hushåll behövs det kopplas till en hushållsmedlem. Det ska bli en ny hushållsmedlem som innehåller den nuvarande användaren och det nya hushållet, och sättas till att vara owner.

**Comment by FridaUltra** [comment]
Mathias ska gå in och lägga till avatar och namn på AddHouseholdModal, så att det ser ut som på NameAndAvatarSelector när man ska välja en avatar. Eftersom vi behöver sätta användaren till ägare så bestämde vi att inte återanvända hela komponenten.

**Comment by MattiasOtter** [comment]
Refaktorerar ut en AvatarModal från kikkis avatarmodal och gör det till en egen fil och gör det möjligt för användaren som skapar ett hushåll att direkt välja avatar och användarnamn och dispatchar både till hushåll och hushållsmedlemmar
